- name: Setup Checkbox

  hosts: jenkins

  gather_facts: false

  tasks:
    - name: Add Mongodb ppa key
      become: yes
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 7F0CEB10

    - name: Add mongodb sources list
      become: yes
      lineinfile:
        dest: /etc/apt/sources.list.d/mongodb-org-3.0.list
        line: "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse"
        state: present
        create: yes

    - name: Install Unzip
      become: yes
      apt: name=unzip state=present update_cache=yes

    - name: Install MongoDB
      become: yes
      apt: name={{ item }}=3.0.7 state=present update_cache=yes
      with_items:
        - mongodb-org
        - mongodb-org-server
        - mongodb-org-shell
        - mongodb-org-mongos
        - mongodb-org-tools

    - name: Installing Python-Pip
      become: yes
      apt:
        pkg: python-pip
        state: latest

    - name: Installing Python pip 3
      become: yes
      apt:
        pkg: python3-pip
        state: latest
    - name: Install the latest pymongo package
      become: yes
      pip: name=pymongo state=latest use_mirrors=no

    - name: Install nginx
      become: yes
      apt:
        pkg: nginx
        state: latest
        update_cache: yes

    - name: Intsall pymongo
      become: yes
      pip:
        name: pymongo
        state: present

    - name: Clone Checkbox
      git:
        repo: "https://{{ lookup('env', 'GITHUB_USERNAME') }}:{{ lookup('env', 'GITHUB_PASSWORD') }}@github.ncsu.edu/tmdement/checkbox.io"
        dest: /home/{{ ansible_user }}/checkbox.io
        force: yes

    - name: Copy the relevant files
      template:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/checkbox.io/server-side/site/"
        force: yes
      with_items:
        - /home/vagrant/share/JenkinsTestAnalysis/templates/generator.js
        - /home/vagrant/share/JenkinsTestAnalysis/templates/studies.json
        - /home/vagrant/share/JenkinsTestAnalysis/templates/votes.json
        - /home/vagrant/share/JenkinsTestAnalysis/templates/coverage.js

    - name: Start MongoDB service
      become: yes
      shell: "systemctl start mongodb"

    - name: Create MongoDb user
      become: yes
      mongodb_user:
        database: "admin"
        name: "{{ lookup('env', 'MONGO_USER')}}"
        password: "{{ lookup('env', 'MONGO_PASSWORD')}}"
        roles: readWriteAnyDatabase,dbAdmin,userAdminAnyDatabase

    - name: Export MONGO_USER environment variable
      become: yes
      shell: "echo \"export MONGO_USER={{ lookup('env', '')}}\" >> /etc/environment"

    - name: Export MONGO_PORT environment variable
      become: yes
      shell: "echo \"export MONGO_PORT=3002\" >> /etc/environment"

    - name: Export MONGO_PASS environment variable
      become: yes
      shell: "echo \"export MONGO_PASSWORD={{ lookup('env', 'MONGO_PASSWORD')}}\" >> /etc/environment"

    - name: Export MAIL_SMTP environment variable
      become: yes
      shell: "echo "export MAIL_SMTP=smtp.gmail.com" >> /etc/environment"

    - name: Export MAIL_USER environment variable
      become: yes
      shell: "echo \"export MAIL_USER={{ lookup('env', 'MAIL_USER') }}\" >> /etc/environment"

    - name: Export MAIL_PASSWORD environment variable
      become: yes
      shell: "echo \"export MAIL_PASSWORD={{ lookup('env', 'MAIL_PASSWORD') }}\" >> /etc/environment"

    - name: Export MONGO_IP environment variable
      become: yes
      shell: "echo \"export MONGO_IP=localhost\" >> /etc/environment"

    - name: install packages
      npm:
        path: "/home/{{ ansible_user }}/checkbox.io/server-side/site"
        state: latest

    - name: update location of public_html into default
      replace:
        dest: /home/{{ ansible_user }}/checkbox.io/local-conf/default
        regexp: '/Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html'
        replace: '/home/{{ ansible_user }}/checkbox.io/public_html'

    - name: Add the votes data into the mongo db database
      shell: "mongoimport --db site --collection votes --drop --file votes.json"
      args:
        chdir: "/home/{{ ansible_user }}/checkbox.io/server-side/site"

    - name: Add the studies data into the mongo db database
      shell: "mongoimport --db site --collection studies --drop --file studies.json"
      args:
        chdir: "/home/{{ ansible_user }}/checkbox.io/server-side/site"

    - name: Copy default to different location
      become: yes
      shell: "cp /home/{{ ansible_user }}/checkbox.io/local-conf/default /etc/nginx/sites-available/default"

    - name: Copy nginx to diferent location
      become: yes
      shell: "cp /home/{{ ansible_user }}/checkbox.io/local-conf/nginx.conf /etc/nginx/nginx.conf"

    - name: restart nginx
      become: yes
      service: name=nginx state=stopped enabled=no

    - name: Remove forever
      become: yes
      npm: name=forever global=yes state=absent

    - name: Install pm2 globally
      become: yes
      npm:
        name: pm2
        global: yes
        state: present

    - name: Install checkbox.io npm packages
      npm:
        path: "/home/{{ ansible_user }}/checkbox.io/server-side/site"

    - name: Install local npm packages
      become: yes
      npm:
        name: "{{ item }}"
        path: "/home/{{ ansible_user }}/checkbox.io/server-side/site"
        state: latest
      with_items:
        - istanbul-middleware
        - esprima
        - request
        - express

    - name: restart nginx
      become: yes
      service: name=nginx state=started enabled=no

    - name: Start the server
      shell: "pm2 start coverage.js"
      args:
        chdir: "/home/{{ ansible_ssh_user }}/checkbox.io/server-side/site/"

    - name: Get Jenkins crumb
      uri:
        url: 'http://127.0.0.1:8081/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
        user: "{{ lookup('env', 'JENKINS_USERNAME') }}"
        password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
        force_basic_auth: yes
        return_content: yes
      register: crumb
    
    - name: Trigger builds
      uri:
        method: POST
        url: "http://127.0.0.1:8081/job/project_checkbox_job/build"
        user: "{{ lookup('env', 'JENKINS_USERNAME') }}"
        password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
        force_basic_auth: yes
        status_code: 201
        headers:
          Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"

#resources: https://docs.mongodb.com/getting-started/shell/tutorial/install-mongodb-on-ubuntu/
#https://stackoverflow.com/questions/20919222/ansible-hangs-when-starting-node-js-server
