---
- hosts: jenkins

  vars_files:
    - /home/vagrant/share/JenkinsTestAnalysis/vars/main.yml
  
  vars:
    num_runs: 100

  tasks:

    - name: Remove FuzzerTool directory if it exists
      file:
        state: absent
        path: "/home/{{ ansible_user }}/FuzzerTool"

    - name: Make a directory for the tool
      file:
        path: "/home/{{ ansible_user }}/FuzzerTool"
        state: directory

    - name: Copy files into FuzzerTool directory
      template:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/FuzzerTool/"
        force: yes
      with_items:
        - /home/vagrant/share/JenkinsTestAnalysis/templates/package.json
        - /home/vagrant/share/JenkinsTestAnalysis/templates/fuzzerTool.js
        - /home/vagrant/share/JenkinsTestAnalysis/templates/testAnalysis.js
        - /home/vagrant/share/JenkinsTestAnalysis/templates/fuzzer.js

    - name: Install node packages
      npm:
        path: "/home/{{ ansible_user }}/FuzzerTool/"
        state: latest

    - name: Install global npm packages
      npm:
        name: shelljs
        global: yes
      become: yes

    - name: Start the FuzzerTool
      become: yes
      shell: 'node fuzzerTool.js; sleep 60'
      args:
        chdir: "/home/{{ ansible_user }}/FuzzerTool/"
      with_sequence: "count={{ num_runs }}"

    - name: Start the Test Analysis FuzzerTool
      become: yes
      shell: "node testAnalysis.js {{ num_runs }}"
      args:
        chdir: "/home/{{ ansible_user }}/FuzzerTool/"
