---
- name: initialize iTrust server

  hosts: itrust

  tasks:
  - name: Step 1 Install maven
    apt: pkg=maven update_cache=yes
    become: yes

  - name: Step 2 Install git
    apt: name=git state=present
    become: yes

  - name: Step 3 Set oracle java repo
    apt_repository: repo='ppa:webupd8team/java' state=present
    become: yes

  - name: Step 4 Update Anyway
    shell: sudo apt-get update
    become: yes

  - name: Step 5 Java license
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: yes

  - name: Step 6 Install Oracle Java 8
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    become: yes

  - name: Step 7 Check if public repo already cloned
    stat:
      path: /home/ubuntu/iTrust
    register: result

  - name: Step 8 Clone iTrust repo
    git: repo=https://{{ lookup('env', 'GITHUB_USERNAME') }}:{{ lookup('env', 'GITHUB_PASSWORD' ) }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2.git dest=/home/{{ ansible_user }}/iTrust
    become: yes
    when: result.stat.isdir is not defined

  - name: Step 9 Install mysql server
    apt: name=mysql-server state=present
    become: yes

  - name: Step 10 Check if db.properties file already exists
    stat:
      path: /home/ubuntu/iTrust/iTrust2/src/main/java/db.properties
    register: result

  - name: Step 11 Copy the contents of db.properties.template file
    command: sudo mv db.properties.template db.properties
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/src/main/java"
    when: result.stat.isdir is not defined

  - name: Step 12 Check if email.properties file already exists
    stat:
      path: /home/ubuntu/iTrust/iTrust2/src/main/java/email.properties
    register: result

  - name: Step 13 Copy the contents of email.properties.template file
    command: sudo mv email.properties.template email.properties
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/src/main/java"
    when: result.stat.isdir is not defined

  - name: Step 14 Check if hibernate.properties file already exists
    stat:
      path: /home/ubuntu/iTrust/iTrust2/src/main/resources/hibernate.properties
    register: result

  - name: Step 15 Copy the contents of hibernate.properties.template file
    command: sudo mv hibernate.properties.template hibernate.properties
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/src/main/resources"
    when: result.stat.isdir is not defined

  - name: Step 16 Update the configuration file for mySQL
    copy: src=/home/ubuntu/JenkinsProvisioner/templates/my.cnf dest=/etc/mysql/my.cnf force=yes
    become: yes

  - name: Step 17 Restart MySQL
    service: name=mysql state=restarted
    become: yes

  - name: Step 18 Run test to verify iTrust Build
    shell: sudo mvn clean test verify checkstyle:checkstyle
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/"
    become: yes

  - name: Step 19 Run process-test-classes
    shell: sudo mvn process-test-classes
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/"
    become: yes

  - name: Step 20 Check if iTrust is running in port 8080
    shell: nohup bash -c "sudo mvn jetty:run" &
    args:
      chdir: "/home/ubuntu/iTrust/iTrust2/"
    become: yes

  # - name: Step 9 set MySQL root password
    # debconf: name='mysql-server' question='mysql-server/root_password' value='root' vtype='password'
    # become: yes

  # - name: Step 10 confirm MySQL root password
    # debconf: name='mysql-server' question='mysql-server/root_password_again' value='root' vtype='password'
    # become: yes

  # - name: Step 18 Update username in email.properties file
    # lineinfile:
      # path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties
      # regexp: '^username '
      # line: 'username = username@gmail.com'

  # - name: Step 18 Update password in email.properties file
    # lineinfile:
      # path: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties
      # regexp: '^password '
      # line: 'password = yourPassword'

  # - name: Step 18 Change password in hibernate.properties file
    # lineinfile:
      # path: /home/vagrant/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
      # regexp: '^hibernate.connection.password = '
      # line: 'hibernate.connection.password = root'

  # - name: Step 19 Change password in db.properties file
    # lineinfile:
      # path: /home/vagrant/iTrust2-v2/iTrust2/src/main/java/db.properties
      # regexp: '^password '
      # line: 'password root'

  # - name: Step 20 Update /etc/mysql/my.cnf file0
    # lineinfile:
      # path: /etc/mysql/my.cnf
      # #line: 'password root'

  # - name: Remove MySQL case sensitivity
    # copy: src=my.cnf dest=/etc/mysql